# Generated by Django 4.1 on 2022-10-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sortTitle', models.CharField(max_length=100)),
                ('birthDate', models.IntegerField()),
                ('deathDate', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=1000)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastModified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
