# Generated by Django 4.1 on 2022-10-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='data/images/')),
                ('thumbnail', models.ImageField(upload_to='data/thumbnails/')),
                ('dateStart', models.IntegerField()),
                ('dateEnd', models.IntegerField(blank=True, null=True)),
                ('placeOfOrigin', models.CharField(max_length=100)),
                ('dimensions', models.CharField(max_length=100)),
                ('mediumDisplay', models.CharField(max_length=100)),
                ('provenanceText', models.CharField(blank=True, default='', max_length=3000)),
                ('isPublicDomain', models.BooleanField(default=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('department', models.CharField(max_length=80)),
                ('artistId', models.IntegerField()),
                ('artistTitle', models.CharField(max_length=200)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastModified', models.DateTimeField(auto_now=True)),
                ('onDisplay', models.BooleanField(default=False)),
            ],
        ),
    ]
