# Generated by Django 4.1 on 2022-10-15 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='artistId',
            new_name='artist_id',
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='artistTitle',
            new_name='artist_title',
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='createdDate',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='dateEnd',
            new_name='date_end',
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='dateStart',
            new_name='date_start',
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='isPublicDomain',
            new_name='is_public_domain',
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='lastModified',
            new_name='last_modified',
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='mediumDisplay',
            new_name='medium_display',
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='onDisplay',
            new_name='on_display',
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='placeOfOrigin',
            new_name='place_of_origin',
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='provenanceText',
            new_name='provenance_text',
        ),
    ]
