# Generated by Django 4.1 on 2022-10-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video', models.FileField(upload_to='data/videos/')),
                ('thumbnail', models.ImageField(upload_to='data/videos/thumbnails/')),
                ('productionDate', models.IntegerField()),
                ('placeOfOrigin', models.CharField(max_length=100)),
                ('length', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=1000)),
                ('isPublicDomain', models.BooleanField(default=False)),
                ('creator', models.CharField(max_length=100)),
                ('subject', models.CharField(default='', max_length=100)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastModified', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
    ]
