# Generated by Django 4.1 on 2022-10-15 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='createdDate',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='isPublicDomain',
            new_name='is_public_domain',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='lastModified',
            new_name='last_modified',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='placeOfOrigin',
            new_name='place_of_origin',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='productionDate',
            new_name='production_date',
        ),
    ]
